spring:
  application:
    name: ms-user
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/dbuser
    username: postgres
    password: abc123


server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - beans
          - env
          - logger

